// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSwimlanes() {
  return window['go']['main']['App']['GetSwimlanes']();
}

export function LoadFromFile() {
  return window['go']['main']['App']['LoadFromFile']();
}

export function UpdateSwimlanes(arg1) {
  return window['go']['main']['App']['UpdateSwimlanes'](arg1);
}
