// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetState():Promise<main.State>;

export function GetSwimlanes():Promise<Array<main.Swimlane>>;

export function LoadFromFile():Promise<Array<main.Swimlane>>;

export function UpdateSwimlanes(arg1:Array<main.Swimlane>):Promise<void>;
